import { groq } from "next-sanity";
import { imageQuery } from "./shared/image";
import { anchorQuery } from "./shared/anchor";
import { linkQuery } from "./shared/link";

// @sanity-typegen-ignore
export const whatWeDoSectionQuery = groq`
  _type == "what-we-do-section" => {
    _type,
    _key,
    ${anchorQuery},
    padding,
    colorVariant,
    background{
      enabled,
      layout,
      border,
      style,
      color,
      fromColor,
      toColor,
      angle,
      image,
      customHeight,
      verticalOffsetPercent
    },
    heading,
    items[]{
      _key,
      interactionMode,
      destination{
        ${linkQuery}
      },
      titleOverride,
      mediaType,
      image{
        ${imageQuery}
      },
      video{
        asset->{
          _id,
          url,
          mimeType,
          originalFilename
        }
      },
      videoPoster{
        ${imageQuery}
      },
      revealTitle,
      revealDescription,
      expandedMediaType,
      expandedImage{
        ${imageQuery}
      },
      expandedVideo{
        asset->{
          _id,
          url,
          mimeType,
          originalFilename
        }
      },
      expandedVideoPoster{
        ${imageQuery}
      },
      mediaFit,
      positionX,
      positionY,
      width,
      mobilePositionX,
      mobilePositionY,
      mobileWidth,
      floatAmount,
      floatDuration,
      project->{
        _id,
        _type,
        title,
        slug,
        image{
          ${imageQuery}
        }
      }
    },
    sizzleReel{
      enabled,
      label,
      href,
      video{
        asset->{
          _id,
          url,
          mimeType,
          originalFilename
        }
      },
      videoPoster{
        ${imageQuery}
      },
      fireGif{
        ${imageQuery}
      }
    },
    figure{
      useUploadedFigureArtwork,
      personImage{
        ${imageQuery}
      },
      armImage{
        ${imageQuery}
      },
      handImage{
        ${imageQuery}
      },
      personWidth,
      personX,
      shoulderX,
      shoulderY,
      handWidth,
      handTipX,
      handTipY,
      handWristX,
      handWristY,
      handRotationOffset,
      armColor,
      armWidth
    }
  }
`;
